//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCardViewPlugin\src\main\java\com\ashera\cardview\CardViewPlugin.java
//

#include "CardViewImpl.h"
#include "CardViewPlugin.h"
#include "J2ObjC_source.h"
#include "WidgetFactory.h"


@implementation ASCardViewPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCardViewPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASCardViewPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASCardViewPlugin = { "CardViewPlugin", "com.ashera.cardview", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASCardViewPlugin;
}

@end

void ASCardViewPlugin_init(ASCardViewPlugin *self) {
  NSObject_init(self);
}

ASCardViewPlugin *new_ASCardViewPlugin_init() {
  J2OBJC_NEW_IMPL(ASCardViewPlugin, init)
}

ASCardViewPlugin *create_ASCardViewPlugin_init() {
  J2OBJC_CREATE_IMPL(ASCardViewPlugin, init)
}

void ASCardViewPlugin_initPlugin() {
  ASCardViewPlugin_initialize();
  ASWidgetFactory_register__WithASIWidget_(new_ASCardViewImpl_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCardViewPlugin)
