//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCardViewPlugin\src\main\java\com\ashera\cardview\CardViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CardViewImpl")
#ifdef RESTRICT_CardViewImpl
#define INCLUDE_ALL_CardViewImpl 0
#else
#define INCLUDE_ALL_CardViewImpl 1
#endif
#undef RESTRICT_CardViewImpl

#if !defined (ASCardViewImpl_) && (INCLUDE_ALL_CardViewImpl || defined(INCLUDE_ASCardViewImpl))
#define ASCardViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASCardViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (void)addForegroundIfNeeded;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)createWrapperViewWithId:(id)wrapperParent
                      withInt:(jint)viewtype;

- (id)createWrapperViewHolderWithInt:(jint)viewType;

- (id)createWrapperViewHolderNativeWithInt:(jint)viewType;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (id)getForeground;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id)nativeAddForeGroundWithASIWidget:(id<ASIWidget>)w;

- (id)nativeCreateViewWithInt:(jint)viewType;

- (void)nativeSetShadowOffsetWithId:(id)myView
                          withFloat:(jfloat)shadowOffset;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCardViewImpl)

inline NSString *ASCardViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCardViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCardViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASCardViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCardViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCardViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASCardViewImpl_init(ASCardViewImpl *self);

FOUNDATION_EXPORT ASCardViewImpl *new_ASCardViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCardViewImpl *create_ASCardViewImpl_init(void);

FOUNDATION_EXPORT void ASCardViewImpl_initWithNSString_(ASCardViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASCardViewImpl *new_ASCardViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCardViewImpl *create_ASCardViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASCardViewImpl_initWithNSString_withNSString_(ASCardViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASCardViewImpl *new_ASCardViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCardViewImpl *create_ASCardViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASCardViewImpl)

@compatibility_alias ComAsheraCardviewCardViewImpl ASCardViewImpl;

#endif

#if !defined (ASCardViewImpl_CardViewExt_) && (INCLUDE_ALL_CardViewImpl || defined(INCLUDE_ASCardViewImpl_CardViewExt))
#define ASCardViewImpl_CardViewExt_

#define RESTRICT_CardView 1
#define INCLUDE_ADXCardView 1
#include "CardView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASCardViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASCardViewImpl_CardViewExt : ADXCardView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASCardViewImpl:(ASCardViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCardViewImpl_CardViewExt)

FOUNDATION_EXPORT void ASCardViewImpl_CardViewExt_initWithASCardViewImpl_(ASCardViewImpl_CardViewExt *self, ASCardViewImpl *outer$);

FOUNDATION_EXPORT ASCardViewImpl_CardViewExt *new_ASCardViewImpl_CardViewExt_initWithASCardViewImpl_(ASCardViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCardViewImpl_CardViewExt *create_ASCardViewImpl_CardViewExt_initWithASCardViewImpl_(ASCardViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCardViewImpl_CardViewExt)

#endif

#pragma pop_macro("INCLUDE_ALL_CardViewImpl")
