//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCardViewPlugin\src\main\java\com\ashera\cardview\CardViewPlugin.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CardViewPlugin")
#ifdef RESTRICT_CardViewPlugin
#define INCLUDE_ALL_CardViewPlugin 0
#else
#define INCLUDE_ALL_CardViewPlugin 1
#endif
#undef RESTRICT_CardViewPlugin

#if !defined (ASCardViewPlugin_) && (INCLUDE_ALL_CardViewPlugin || defined(INCLUDE_ASCardViewPlugin))
#define ASCardViewPlugin_

@interface ASCardViewPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCardViewPlugin)

FOUNDATION_EXPORT void ASCardViewPlugin_init(ASCardViewPlugin *self);

FOUNDATION_EXPORT ASCardViewPlugin *new_ASCardViewPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCardViewPlugin *create_ASCardViewPlugin_init(void);

FOUNDATION_EXPORT void ASCardViewPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCardViewPlugin)

@compatibility_alias ComAsheraCardviewCardViewPlugin ASCardViewPlugin;

#endif

#pragma pop_macro("INCLUDE_ALL_CardViewPlugin")
